### ISSUE TITLE
Setup failed for custom integration kingspan_watchman_sensit: Requirements for kingspan_watchman_sensit not found: ['kingspan-connect-sensor==2.1.1'].

### ISSUE THREAD

**Issue by jasonmadigan** [masaccio/ha-kingspan-watchman-sensit#6]
Similar to https://github.com/masaccio/ha-kingspan-watchman-sensit/issues/4 - this time with this month's release, HA 2023.6.

**Comment by natkins76** [comment]
Same here after applying HA core update 2023.6

**Comment by masaccio** [comment]
Can you confirm you see an additional log message like this:

`
Unable to install package kingspan-connect-sensor==2.1.1: error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [57 lines of output] Traceback (most recent call last): File "/tmp/pip-build-env-i320mfup/overlay/lib/python3.11/site-packages/numpy/core/__init__.py", line 23, in <module> from . import multiarray File "/tmp/pip-build-env-i320mfup/overlay/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module> from . import overrides File "/tmp/pip-build-env-i320mfup/overlay/lib/python3.11/site-packages/numpy/core/overrides.py", line 6, in <module> from numpy.core._multiarray_umath import ( ImportError: Error loading shared library /tmp/pip-build-env-i320mfup/overlay/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-musl.so: Operation not permitted During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module> main() File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) ^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-i320mfup/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=['wheel']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-i320mfup/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires self.run_setup() File "/tmp/pip-build-env-i320mfup/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup self).run_setup(setup_script=setup_script) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-build-env-i320mfup/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup exec(code, locals()) File "<string>", line 18, in <module> File "/tmp/pip-build-env-i320mfup/overlay/lib/python3.11/site-packages/numpy/__init__.py", line 140, in <module> from . import core File "/tmp/pip-build-env-i320mfup/overlay/lib/python3.11/site-packages/numpy/core/__init__.py", line 49, in <module> raise ImportError(msg) ImportError: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.11 from "/usr/local/bin/python3" * The NumPy version is: "1.23.2" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. Original error was: Error loading shared library /tmp/pip-build-env-i320mfup/overlay/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-x86_64-linux-musl.so: Operation not permitted [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip.
`

For some reason one of my dependencies (NumPy) is not installing.

**Comment by masaccio** [comment]
On the assumption that it's NumPy failing to install, I've changed the underlying library to not depend upon this and propagated the changes into the HA component. v1.4.4 in HACS fixes the install for me.
